### ISSUE TITLE
Example of implementing truepy

### ISSUE THREAD

**Issue by ckdanny** [moses-palmer/truepy#1]
Can you provide some example/sample program to implement the truepy ?

**Comment by moses-palmer** [comment]
I have pushed a few local commits, updated the documentation and made a new release.

Please see the README for more extensive documentation. I will keep this issue open a few days. If you have any suggestions for improvements, please post them here and I will try to include them in the documentation, otherwise I will just close this issue.

**Comment by ckdanny** [comment]
Hi @moses-palmer ,
Thanks for your quick response!
I generate the cert(.pem) and key(.key)
with
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out certificate.pem`

and use the code:

``` python
from cryptography.hazmat import backends
# from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import load_pem_private_key
import pem
from truepy import LicenseData, License


# Load the certificate
with open('certificate.pem', 'r') as f:
    certificate = f.read()

# Load the private key
with open('key.pem', 'rb') as f:
    key = load_pem_private_key(
        f.read(),
        password='abc',
        backend=backends.default_backend())
# certificate = pem.parse_file("certificate.pem")
# key = pem.parse_file("key.pem")

# Issue the license
license = License.issue(
    certificate,
    key,
    license_data=LicenseData('2016-8-01T00:00:00', '2020-10-01T00:00:00'))
#
# Store the license
with open('license.key', 'wb') as f:
    license.store(f, b'LicensePassword')

```

However, the error is occurred in `load_pem_private_key`:

```
From cffi callback <function _pem_password_cb at 0x03202E88>:
Traceback (most recent call last):
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 96, in _pem_password_cb
    pw_buf[:len(ud.password)] = ud.password
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:/Programming Project/Python/License Manager/main.py", line 17, in <module>
    backend=backends.default_backend())
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\primitives\serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\backends\multibackend.py", line 289, in load_pem_private_key
    return b.load_pem_private_key(data, password)
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1033, in load_pem_private_key
    password,
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1202, in _load_key
    self._handle_key_loading_error()
  File "C:\Users\dannychan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1274, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.
```

May I know if you have any idea on this problem? Thanks!

**Comment by moses-palmer** [comment]
The password must be a byte buffer, so replace password='abc' with
password=b'abc'. When I have time, I will update the examples to be copy
paste'able on all supported versions of Python.

**Comment by JoosaT** [comment]
> When I have time, I will update the examples to be copy
> paste'able on all supported versions of Python.

Could you provide an example of issuing license with Python 3?
Here is my code:

```
from cryptography.hazmat import backends
from cryptography.hazmat.primitives import serialization

from truepy import LicenseData, License


# Load the certificate
with open('certificate.pem', 'r') as f:
    certificate = f.read()

# Load the private key
with open('key.pem', 'rb') as f:
    key = serialization.load_pem_private_key(
        f.read(),
        password=b'fj350fkdl3t3',
        backend=backends.default_backend())

# Issue the license
license = License.issue(
    certificate,
    key,
    license_data=LicenseData(
        '2016-10-01T00:00:00',
        '2020-10-01T00:00:00'))

# Store the license
with open('license.key', 'wb') as f:
    license.store(f, b'gj349tigi50f')

```

And here is what I get

```
Traceback (most recent call last):
  File "issue_license.py", line 24, in <module>
    '2020-10-01T00:00:00'))
  File "C:\Users\joosa\.virtualenvs\mvkit-gglIikhh\lib\site-packages\truepy\_license.py", line 142, in issue
    certificate = self._certificate(certificate)
  File "C:\Users\joosa\.virtualenvs\mvkit-gglIikhh\lib\site-packages\truepy\_license.py", line 233, in _certificate
    backends.default_backend())
  File "C:\Users\joosa\.virtualenvs\mvkit-gglIikhh\lib\site-packages\cryptography\x509\base.py", line 50, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "C:\Users\joosa\.virtualenvs\mvkit-gglIikhh\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1134, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "C:\Users\joosa\.virtualenvs\mvkit-gglIikhh\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 449, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str

```

**Comment by moses-palmer** [comment]
I appears that I have had very little time over the last two years ;-)

Anyway, the error happens not in *truepy* but in *cryptography*. As the error message states, the certificate data must be `bytes`, not `str`. Just change line 8 from `with open('certificate.pem', 'r') as f:` to `with open('certificate.pem', 'rb') as f:`.
