### ISSUE TITLE
Do the tool support parse and verify license that is generated by java?

### ISSUE THREAD

**Issue by ShaolongTan** [moses-palmer/truepy#3]
Hi, 

    I have a license that is generate by java package TrueLicense, but I get below error message when I try to parse/verify it by this tool. Do the tool support the license?

Error message:
Traceback (most recent call last):
  File "truepy_varify.py", line 16, in <module>
    license = License.load(f, b'************')
  File "/usr/lib/python2.7/site-packages/truepy/_license.py", line 295, in load
    return deserialize(element)
  File "/usr/lib/python2.7/site-packages/truepy/_bean.py", line 239, in deserialize
    return deserializer(element)
  File "/usr/lib/python2.7/site-packages/truepy/_bean_serializers.py", line 159, in object_deserializer
    element)
  File "/usr/lib/python2.7/site-packages/truepy/_bean_serializers.py", line 118, in default_bean_deserialize
    return self(**properties)
  File "/usr/lib/python2.7/site-packages/truepy/_license.py", line 100, in __init__
    self.data = deserialize(license_data_xml[0])
  File "/usr/lib/python2.7/site-packages/truepy/_bean.py", line 239, in deserialize
    return deserializer(element)
  File "/usr/lib/python2.7/site-packages/truepy/_bean_serializers.py", line 159, in object_deserializer
    element)
  File "/usr/lib/python2.7/site-packages/truepy/_bean_serializers.py", line 115, in default_bean_deserialize
    for e in element.findall('.//void')}
  File "/usr/lib/python2.7/site-packages/truepy/_bean_serializers.py", line 115, in <dictcomp>
    for e in element.findall('.//void')}
  File "/usr/lib/python2.7/site-packages/truepy/_bean.py", line 243, in deserialize
    raise ValueError('unknown XML fragment: %s', ElementTree.tostring(element))
ValueError: ('unknown XML fragment: %s', '<object idref="X500Principal0" />\n  ')

I check the truepy code. The reason is "<object idref="X500Principal0" />" xml element don't include "class" attribute. How I can resolve the issue? Thanks you.

**Comment by moses-palmer** [comment]
What version of *TrueLicense* do you use? Please note that only version 1 is supported.
